apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
  namespace: hotel-dev
spec:
  template:
    spec:
      containers:
        - name: kong-migration
          image: kong:3.4
          command:
            - /bin/sh
            - -c
            - |
              echo "=== Environment Variables ==="
              env | sort
              echo "=== Running Migration ==="
              kong migrations bootstrap
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: kong-gateway-config
            - configMapRef:
                name: env-config
            - configMapRef:
                name: app-config
          env:
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRESQL_DB_HOST
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: kong-gateway-secrets
                  key: POSTGRESQL_DB_USERNAME
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-gateway-secrets
                  key: POSTGRESQL_DB_PASSWORD
            - name: KONG_PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_DB_NAME
            - name: KONG_PG_SCHEMA
              value: "kong_gateway"
            - name: KONG_PG_SSL
              value: "on"
            - name: KONG_PG_SSL_VERIFY
              value: "off"
      restartPolicy: OnFailure