apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: hotel-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong:3.4
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - name: kong-plugins
              mountPath: /usr/local/share/lua/5.1/kong/plugins/custom-auth
          envFrom:
            - configMapRef:
                name: kong-gateway-config
            - configMapRef:
                name: env-config
            - configMapRef:
                name: app-config
          env:
            - name: KONG_PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRESQL_DB_HOST
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: kong-gateway-secrets
                  key: POSTGRESQL_DB_USERNAME
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-gateway-secrets
                  key: POSTGRESQL_DB_PASSWORD
            - name: KONG_PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRESQL_DB_NAME
      volumes:
        - name: kong-plugins
          configMap:
            name: kong-custom-plugins